"""Provision runtime workspace files from Agent config and user-authored templates."""

from __future__ import annotations

import json
import threading
from dataclasses import dataclass, field
from importlib.resources import files as pkg_files
from pathlib import Path
from typing import Any

from PhyAgentOS.config.schema import Config
from PhyAgentOS.runtime.schemas.common import utc_now
from PhyAgentOS.runtime.state_io.atomic_file import atomic_write_text
from PhyAgentOS.runtime.state_io.markdown_yaml import read_yaml_block, write_yaml_block
from PhyAgentOS.runtime.watchdog.supervisor import WatchdogSupervisor

RUNTIME_TEMPLATE_NAMES = ("TARGETS.md", "SKILLS.md")
RUNTIME_CONFIG_TEMPLATE_NAMES = (
    "configs/runtime/contracts/libero_real.runtime.yaml",
    "configs/runtime/contracts/minecraft.runtime.yaml",
)
_RUNTIME_INSTRUCTIONS = """# Runtime Protocol

This file is generated by PhyAgentOS for the Agent. It describes how to queue
runtime sessions. Do not use this file as runtime state.

## Runtime Files

- `TARGETS.md`: user-maintained target registry.
- `SKILLS.md`: available runtime skills.
- `SESSIONS.md`: runtime session queue; the watchdog claims `pending` sessions.
- `ENVIRONMENT.md`: runtime environment state. It is created empty, then the
  runtime manager writes a target registry snapshot. Scene/object state is
  updated only by runtime/perception writers.

## Creating A Session

When the user asks to execute an enabled runtime target, first read the current
`SESSIONS.md`, then use `write_file` (NOT `edit_file`) to rewrite the entire
file with your new session appended to the `sessions` list. Keep existing
sessions and results intact.

Required shape:

```yaml
version: runtime_sessions_v1
sessions:
  - session_id: unique_short_id
    goal_id: optional_goal_id
    target_ref: target://target_id_from_TARGETS
    skill_ref: skill://skill_id_from_SKILLS
    task_description: user-facing task description
    status: pending
    priority: normal
    timeouts:
      queue_timeout_s: 30
      preflight_timeout_s: 20
      execute_timeout_s: 300
      policy_timeout_s: 10
    retry:
      max_retries: 0
      attempted: 0
    routing:
      target_endpoint: targetws://target-host:9002
      policy_endpoint: openpi://policy-host:8000
      adapter_resolution: strict_auto
      adapter_overrides: null
    execution:
      max_steps: 200
      replan_every_steps: 5
      action_chunk_mode: chunk_buffer
      chunk_switch_mode: hard_switch
    runtime_hints:
      perception_queries: []
      force_environment_refresh: false
      preferred_replan_every_steps: 5
    safety_profile:
      profile: default_simulation
      workspace_bounds: default
      stop_on_policy_timeout: true
    result: {}
```

Rules:

- Read `TARGETS.md` and `SKILLS.md` before creating a session. Read
  `ENVIRONMENT.md` for the latest target runtime snapshot.
- Use only targets whose `TARGETS.md` entry has `enabled: true`.
- `target_ref` must match an id in `TARGETS.md`; `skill_ref` must be listed in
  that target's `supported_skills`.
- Use endpoint values declared in `TARGETS.md` unless the user explicitly
  provides a different endpoint.
- Do not manually edit `ENVIRONMENT.md`; it is runtime state managed by
  PhyAgentOS.
- Each action in `perception_queries` must use `type` (not `action`) for the
  action name, and `params` for parameters. Example:
  `{type: move, params: {forward: 5}}` for relative movement, or
  `{type: collect, params: {block_type: oak_log, count: 5}}`.
  See `EMBODIED.md` for the full list of supported actions.
"""


@dataclass
class RuntimeWorkspaceReport:
    workspace: Path
    created: list[str] = field(default_factory=list)
    skipped: list[str] = field(default_factory=list)
    updated: list[str] = field(default_factory=list)
    disabled_targets: list[str] = field(default_factory=list)
    enabled_targets: list[str] = field(default_factory=list)
    watchdog_started: bool = False


class RuntimeWorkspaceManager:
    """Create runtime workspace files and optionally supervise sessions."""

    def __init__(self, config: Config):
        self.config = config
        self.workspace = config.runtime_workspace_path
        self._watchdog: BackgroundWatchdog | None = None

    def provision(self) -> RuntimeWorkspaceReport:
        report = RuntimeWorkspaceReport(workspace=self.workspace)
        if not self.config.runtime.enabled:
            return report
        self.workspace.mkdir(parents=True, exist_ok=True)
        templates = pkg_files("PhyAgentOS") / "templates"
        self._copy_missing_templates(templates, report)
        self._deploy_embodied_from_targets(templates, report)
        self.write_runtime_instructions(report)
        self._ensure_empty_sessions(report)
        self._ensure_empty_environment(report)
        self._apply_target_enabled_overrides(report)
        self.write_environment_targets_snapshot(report)
        return report

    def start_watchdog(self) -> RuntimeWorkspaceReport:
        report = self.provision()
        if not self.config.runtime.enabled or not self.config.runtime.autostart_watchdog:
            return report
        if self._watchdog is None:
            self._watchdog = BackgroundWatchdog(
                self.workspace,
                environment_workspace=self.config.workspace_path,
                poll_interval_s=self.config.runtime.watchdog_poll_interval_s,
            )
            self._watchdog.start()
            report.watchdog_started = True
        return report

    def stop_watchdog(self) -> None:
        if self._watchdog is None:
            return
        self._watchdog.stop()
        self._watchdog = None

    def _copy_missing_templates(self, templates: Any, report: RuntimeWorkspaceReport) -> None:
        for name in RUNTIME_TEMPLATE_NAMES:
            src = templates / name
            dest = self.workspace / name
            if dest.exists():
                report.skipped.append(name)
                continue
            dest.write_text(src.read_text(encoding="utf-8"), encoding="utf-8")
            report.created.append(name)
        for name in RUNTIME_CONFIG_TEMPLATE_NAMES:
            src = templates.joinpath(*Path(name).parts)
            dest = self.workspace / name
            if dest.exists():
                report.skipped.append(name)
                continue
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(src.read_text(encoding="utf-8"), encoding="utf-8")
            report.created.append(name)

    _GAME_EMBODIED_MAP = {"minecraft_java_env": "configs/runtime/embodied/minecraft.md"}

    def _deploy_embodied_from_targets(
        self, templates: Any, report: RuntimeWorkspaceReport
    ) -> None:
        targets_path = self.workspace / "TARGETS.md"
        if not targets_path.exists():
            return
        try:
            document = read_yaml_block(targets_path)
        except Exception:
            return
        targets = document.get("targets")
        if not isinstance(targets, list):
            return
        target_ids = {
            t["id"] for t in targets if isinstance(t, dict) and isinstance(t.get("id"), str)
        }
        for target_id, embodied_src_name in self._GAME_EMBODIED_MAP.items():
            if target_id not in target_ids:
                continue
            src = templates / embodied_src_name
            if not src.exists():
                continue
            dest = self.workspace / "EMBODIED.md"
            content = src.read_text(encoding="utf-8")
            existed = dest.exists()
            if existed and dest.read_text(encoding="utf-8") == content:
                continue
            dest.write_text(content, encoding="utf-8")
            (report.updated if existed else report.created).append("EMBODIED.md")

    def _ensure_empty_sessions(self, report: RuntimeWorkspaceReport) -> None:
        sessions_path = self.workspace / "SESSIONS.md"
        if sessions_path.exists():
            report.skipped.append("SESSIONS.md")
            return
        write_yaml_block(
            sessions_path,
            "Runtime Sessions",
            {"version": "runtime_sessions_v1", "sessions": []},
        )
        report.created.append("SESSIONS.md")

    def _ensure_empty_environment(self, report: RuntimeWorkspaceReport) -> None:
        environment_path = self.workspace / "ENVIRONMENT.md"
        if environment_path.exists():
            report.skipped.append("ENVIRONMENT.md")
            return
        environment_path.write_text("", encoding="utf-8")
        report.created.append("ENVIRONMENT.md")

    def write_runtime_instructions(self, report: RuntimeWorkspaceReport | None = None) -> RuntimeWorkspaceReport:
        report = report or RuntimeWorkspaceReport(workspace=self.workspace)
        path = self.workspace / "RUNTIME.md"
        existed = path.exists()
        path.write_text(_RUNTIME_INSTRUCTIONS, encoding="utf-8")
        (report.updated if existed else report.created).append("RUNTIME.md")
        return report

    def _apply_target_enabled_overrides(self, report: RuntimeWorkspaceReport) -> None:
        overrides = dict(self.config.runtime.target_enabled)
        if not overrides:
            return
        targets_path = self.workspace / "TARGETS.md"
        if not targets_path.exists():
            return
        document = read_yaml_block(targets_path)
        targets = document.get("targets")
        if not isinstance(targets, list):
            return
        changed = False
        for target in targets:
            if not isinstance(target, dict):
                continue
            target_id = target.get("id")
            if not isinstance(target_id, str) or target_id not in overrides:
                continue
            enabled = bool(overrides[target_id])
            if target.get("enabled") != enabled:
                target["enabled"] = enabled
                changed = True
            if enabled:
                report.enabled_targets.append(target_id)
            else:
                report.disabled_targets.append(target_id)
        if changed:
            write_yaml_block(targets_path, "Runtime Targets", document)
            report.updated.append("TARGETS.md")

    def write_environment_targets_snapshot(
        self,
        report: RuntimeWorkspaceReport | None = None,
    ) -> RuntimeWorkspaceReport:
        report = report or RuntimeWorkspaceReport(workspace=self.workspace)
        targets_path = self.workspace / "TARGETS.md"
        if not targets_path.exists():
            return report
        try:
            document = read_yaml_block(targets_path)
        except Exception:
            return report
        targets = document.get("targets")
        if not isinstance(targets, list):
            return report

        now = utc_now().isoformat()
        payload = {
            "schema_version": "PhyAgentOS.environment.v2",
            "updated_at": now,
            "targets": {
                str(target["id"]): self._target_snapshot(target, now)
                for target in targets
                if isinstance(target, dict) and isinstance(target.get("id"), str)
            },
        }
        env_path = self.workspace / "ENVIRONMENT.md"
        existed = env_path.exists()
        text = (
            "# Environment State\n\n"
            "Auto-updated by PhyAgentOS runtime workspace manager.\n\n"
            f"```json\n{json.dumps(payload, indent=2, ensure_ascii=False)}\n```\n"
        )
        atomic_write_text(env_path, text)
        if "ENVIRONMENT.md" not in report.created and "ENVIRONMENT.md" not in report.updated:
            (report.updated if existed else report.created).append("ENVIRONMENT.md")
        return report

    def _target_snapshot(self, target: dict[str, Any], now: str) -> dict[str, Any]:
        runtime = target.get("runtime") if isinstance(target.get("runtime"), dict) else {}
        config = target.get("config") if isinstance(target.get("config"), dict) else {}
        enabled = bool(target.get("enabled", True))
        endpoint = runtime.get("target_endpoint")
        target_class = target.get("target_class")
        if enabled:
            if target_class == "local":
                # Local targets are "configured" only when config block
                # contains actual values (not just default scaffolding).
                has_config = any(
                    v for v in config.values()
                    if isinstance(v, str) and v.strip()
                )
                status = "configured" if has_config else "unconfigured"
            elif endpoint:
                status = "configured"
            else:
                status = "unconfigured"
        else:
            status = "disabled"
        return {
            "target_id": target.get("id"),
            "enabled": enabled,
            "target_class": target_class,
            "target_kind": target.get("target_kind"),
            "workspace": target.get("workspace"),
            "supported_skills": list(target.get("supported_skills") or []),
            "connection_state": {
                "status": status,
                "endpoint": endpoint,
                "checked_at": now,
                "source": "TARGETS.md",
            },
            "runtime": {
                "target_runtime": runtime.get("target_runtime"),
                "target_adapter": runtime.get("target_adapter"),
                "runtime_contract_ref": str(runtime.get("runtime_contract_ref") or ""),
            },
            "benchmark": {
                key: config[key]
                for key in ("benchmark_name", "task_id", "init_state_id")
                if key in config
            },
        }


class BackgroundWatchdog:
    """Run WatchdogSupervisor in a daemon thread owned by the Agent process."""

    def __init__(
        self,
        workspace: Path,
        *,
        environment_workspace: Path,
        poll_interval_s: float,
    ):
        self.workspace = workspace
        self.environment_workspace = environment_workspace
        self.poll_interval_s = max(0.05, float(poll_interval_s))
        self._stop = threading.Event()
        self._thread = threading.Thread(target=self._run, name="phyagentos-runtime-watchdog", daemon=True)

    def start(self) -> None:
        self._thread.start()

    def stop(self) -> None:
        self._stop.set()
        self._thread.join(timeout=2.0)

    def _run(self) -> None:
        supervisor = WatchdogSupervisor(self.workspace, environment_workspace=self.environment_workspace)
        while not self._stop.is_set():
            try:
                ran = supervisor.run_once()
            except Exception:
                ran = False
            if not ran:
                self._stop.wait(self.poll_interval_s)
